BASELINE_FEATURE_COLUMNS = [
    # Context
    'isContributorAnonymous',
    'rawCommentLength',
    'sizeChange',
    'timeSinceLastArticleEdit',
    'timeOfDay',
    'dayOfWeek',
    'timeSinceFirstArticleEdit',
    'timeSinceReverted',
    'editRatio',
    'hasPreviousSameContributor',
    # Text
    'digitRatio',
    'alphanumericRatio',
    'uppercaseRatio',
    'uppercaseToLowercaseRatio',
    'longCharSeq',
    'lengthOfLongestToken',
    'newWordFrequency',
    'LZWCompressionRate',
    'kldOfCharDistribution',
    'previousLength',
    # Language
    'vulgarWordFrequencyInComment',
    'vulgarWordFrequencyInTables',
    'vulgarWordImpactInTables',
    'personalPronounFrequencyInComment',
    'personalPronounFrequencyInTable',
    'personalPronounImpactInTable',
    # Ref: Colloquial, high bias
    'superlativeWordFrequencyInComment',
    'superlativeWordFrequencyInTable',
    'superlativeWordImpactInTable',
    'sexualWordFrequencyInComment',
    'sexualWordFrequencyInTables',
    'sexualWordImpactInTables',
    'averageAllBadWordFrequencyInComment',
    'averageAllBadWordFrequencyInTable',
    'averageAllBadWordImpactInTable',
    # Ref: Good words
    'wikiSyntaxElementFrequencyInTable',
    'wikiSyntaxElementImpactInTable',
    'wikiSyntaxElementFrequencyInComment',
    'revertInComment'
]
